/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список промптов с фильтрами и пагинацией */
        get: operations["UsersController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Заблокировать пользователя */
        patch: operations["UsersController_blockUser"];
        trace?: never;
    };
    "/api/users/{id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Разблокировать пользователя */
        patch: operations["UsersController_unblockUser"];
        trace?: never;
    };
    "/api/auth/register/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerByPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/confirm/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendConfirmLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин по email + пароль */
        post: operations["AuthController_loginByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин по телефону + пароль */
        post: operations["AuthController_loginByPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить OTP-код для телефона */
        post: operations["AuthController_requestPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access-токен по refresh (cookie) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти и отозвать сессию */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_redirectToYandex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_yandexCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить письмо для восстановления пароля */
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтвердить восстановление пароля */
        post: operations["AuthController_confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список промптов с фильтрами и пагинацией */
        get: operations["PromptsController_findMany"];
        put?: never;
        /** Создать новый промпт (только админ) */
        post: operations["PromptsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один промпт по id */
        get: operations["PromptsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить промпт (только админ) */
        delete: operations["PromptsController_remove"];
        options?: never;
        head?: never;
        /** Обновить промпт (только админ) */
        patch: operations["PromptsController_update"];
        trace?: never;
    };
    "/api/files/ai-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesController_aiUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить метаданные файла */
        get: operations["FilesController_getOne"];
        put?: never;
        post?: never;
        /** Удалить файл по ID */
        delete: operations["FilesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список генераций с фильтрами и пагинацией */
        get: operations["ModelJobController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/last-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить последние несколько генераций запросившего пользователя */
        get: operations["ModelJobController_lastGenerations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один процесс по id */
        get: operations["ModelJobController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-edit-by-prompt-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageEditByPromptId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-edit-by-prompt-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageEditByPromptText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-edit-by-style-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageEditByStyleReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageGenerateByPromptText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-admin-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startAdminGenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список платежей с фильтрами и пагинацией */
        get: operations["UserTokenTransactionsController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/token-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список доступных пакетов токенов
         * @description Возвращает набор пакетов токенов, которые отображаются пользователю на фронте.
         */
        get: operations["PricingController_getTokenPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий */
        get: operations["CategoriesController_findMany"];
        put?: never;
        /** Создать новую категорию (только админ) */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один промпт по id */
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить категорию (только админ) */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /** Обновить категорию (только админ) */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/api/payments/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать платёж за пакет токенов */
        post: operations["PaymentsController_createTokensPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список платежей с фильтрами и пагинацией */
        get: operations["PaymentsController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о платеже */
        get: operations["PaymentsController_getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/full/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить полную информацию о платеже */
        get: operations["PaymentsController_getFullPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить платеж */
        post: operations["PaymentsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/yookassa/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вебхук от YooKassa
         * @description Обрабатывает события YooKassa (payment.succeeded, payment.canceled и т.д.). Вызывается YooKassa, а не фронтом.
         */
        post: operations["PaymentsController_yookassaWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}/refund-tokens/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Предпросмотр: сколько токенов и денег можно вернуть по платежу */
        get: operations["PaymentsController_getRefundTokensPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}/refund-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сделать частичный рефанд по токенам */
        post: operations["PaymentsController_refundTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить возврат платежа полностью/частично */
        post: operations["PaymentsController_refundPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/yookassa/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Внутренний вебхук от платежного шлюза (проксирующего YooKassa)
         * @description Используется только нашим RU-шлюзом. Защищён секретным заголовком.
         */
        post: operations["InternalYookassaController_handleInternalWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginationMetaDto: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
        /** @enum {string} */
        UserRole: "user" | "admin";
        UserDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example user@example.com */
            email?: string | null;
            yandexId?: string | null;
            /** @example +79998887766 */
            phone?: string | null;
            /** @example user */
            role: components["schemas"]["UserRole"];
            /**
             * @description Баланс токенов
             * @example 100
             */
            tokens: number;
            /**
             * @description Активен ли пользователь
             * @example true
             */
            isActive: boolean;
            /**
             * @description Подтверждён ли email
             * @example false
             */
            isEmailVerified: boolean;
            /**
             * @description Подтверждён ли телефон
             * @example true
             */
            isPhoneVerified: boolean;
            /**
             * @description Заблокирован ли пользователь
             * @example false
             */
            isBlocked: boolean;
            /**
             * Format: date-time
             * @description Дата блокировки пользователя
             */
            blockedAt?: string | null;
            /** @description Причина блокировки (видна только администраторам) */
            blockedReason?: string | null;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        BlockUserDto: {
            /**
             * @description Причина блокировки (опционально)
             * @example Спам / злоупотребление сервисом
             */
            reason?: string | null;
        };
        RegisterByEmailDto: {
            /** @example user@example.com */
            email: string;
            /** @example ПарольПароль123! */
            password: string;
        };
        RegisterByPhoneDto: {
            /** @example +79998887766 */
            phone: string;
            /**
             * @description Пароль (необязателен, если используется вход по OTP)
             * @example secretPassword123
             */
            password?: string;
        };
        ResendConfirmEmailDto: {
            /** @example user@example.com */
            email: string;
        };
        LoginByEmailDto: {
            /** @example user@example.com */
            email: string;
            /** @example StrongPass123! */
            password: string;
        };
        AuthResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            user: components["schemas"]["UserDto"];
        };
        LoginByPhoneDto: {
            /** @example +79998887766 */
            phone: string;
            /** @example Secret123 */
            password: string;
        };
        RequestPhoneOtpDto: {
            /** @example +79998887766 */
            phone: string;
        };
        VerifyPhoneOtpDto: {
            /** @example +79998887766 */
            phone: string;
            /** @example 123456 */
            code: string;
        };
        RequestPasswordResetDto: {
            /** @example user@example.com */
            email: string;
        };
        ConfirmPasswordResetDto: {
            /** @example f4581a6a-a33a-48cd-a07b-5638d9f7c649 */
            userId: string;
            /** @example b471548384c7428bb90a8e8e5c2b9c2f1e3b4a8760f8d12e8fa7b2c2f48a8d91 */
            token: string;
            /**
             * @description Новый пароль пользователя
             * @example NewStrongPassword123!
             */
            password: string;
        };
        FileDto: {
            /** @example uploads/2025/09/04/photo.png */
            key: string;
            /** @example my-bucket */
            bucket: string;
            /**
             * Format: uri
             * @example https://cdn.example.com/uploads/2025/09/04/photo.png
             */
            url?: string | null;
            /** @example image/png */
            contentType?: string;
            /**
             * @description Размер файла в байтах
             * @example 204800
             */
            size?: number;
            /**
             * @description Ширина файла в пикселях
             * @example 1024
             */
            widthPx?: number | null;
            /**
             * @description Высота файла в пикселях
             * @example 768
             */
            heightPx?: number | null;
            /** @example user-123 */
            ownerId?: Record<string, never> | null;
            /** @example {
             *       "width": 400,
             *       "height": 300
             *     } */
            meta?: Record<string, never> | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PromptType: "image-to-image" | "text-to-image" | "text-to-text";
        /** @enum {string} */
        ModelType: "OPENAI" | "GEMINI";
        CategoryDto: {
            /** @example Мультипликация */
            name: string;
            /** @example Обработка изображения в рисовке мультфильмов */
            description: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PromptResponseDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            beforeImageId: string;
            beforeImage: components["schemas"]["FileDto"];
            beforePreviewImageId: string;
            beforePreviewImage: components["schemas"]["FileDto"];
            afterImageId: string;
            afterImage: components["schemas"]["FileDto"];
            afterPreviewImageId: string;
            afterPreviewImage: components["schemas"]["FileDto"];
            type: components["schemas"]["PromptType"];
            model: components["schemas"]["ModelType"];
            /** @description Текст промпта */
            text: string;
            categoryId: string;
            category: components["schemas"]["CategoryDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uri */
            beforePreviewImageUrl: string | null;
            /** Format: uri */
            afterPreviewImageUrl: string | null;
        };
        PromptDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            beforeImageId: string;
            beforeImage: components["schemas"]["FileDto"];
            beforePreviewImageId: string;
            beforePreviewImage: components["schemas"]["FileDto"];
            afterImageId: string;
            afterImage: components["schemas"]["FileDto"];
            afterPreviewImageId: string;
            afterPreviewImage: components["schemas"]["FileDto"];
            type: components["schemas"]["PromptType"];
            model: components["schemas"]["ModelType"];
            /** @description Текст промпта */
            text: string;
            categoryId: string;
            category: components["schemas"]["CategoryDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePromptDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            beforeImageId: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            afterImageId: string;
            /** @description Промпт шаблона */
            text: string;
            model: components["schemas"]["ModelType"];
            /** @description Категория */
            categoryId: string;
        };
        UpdatePromptDto: {
            /** @example Аниме-портрет */
            title?: string;
            /** @example Мягкое освещение, крупный план */
            description?: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            beforeImageId?: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            afterImageId?: string;
            /** @description Промпт шаблона */
            text?: string;
            model?: components["schemas"]["ModelType"];
            /** @description Категория */
            categoryId?: string;
        };
        UploadDto: {
            /** Format: binary */
            file: string;
        };
        DeleteFileResponseDto: {
            /** @example true */
            ok: boolean;
            /**
             * @description UUID удалённого файла
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            id: string;
        };
        /** @enum {string} */
        ModelJobType: "image-edit-by-prompt-id" | "image-edit-by-prompt-text" | "image-edit-by-style-reference" | "image-generate-by-prompt-text";
        /** @enum {string} */
        ModelJobStatusType: "queued" | "processing" | "succeeded" | "failed";
        ModelJobFile: Record<string, never>;
        /** @enum {string} */
        ModelJobTariffCode: "USER" | "ADMIN";
        ModelJobDto: {
            model: components["schemas"]["ModelType"];
            type: components["schemas"]["ModelJobType"];
            status: components["schemas"]["ModelJobStatusType"];
            text: string | null;
            /** @example 2:3 */
            aspectRatio: string | null;
            /** @example 1K */
            imageSize: string | null;
            promptId: string | null;
            prompt: components["schemas"]["PromptDto"] | null;
            /** @example user-123 */
            userId: string;
            user: components["schemas"]["UserDto"] | null;
            files: components["schemas"]["ModelJobFile"][] | null;
            outputText: string | null;
            tariffCode: components["schemas"]["ModelJobTariffCode"];
            /** @example 8 */
            tokensCharged: number;
            usedTokens: Record<string, never> | null;
            error: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            resultsExpireAt: string | null;
            /** Format: date-time */
            resultsDeletedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ModelJobWithPreviewFileDto: {
            model: components["schemas"]["ModelType"];
            type: components["schemas"]["ModelJobType"];
            status: components["schemas"]["ModelJobStatusType"];
            text: string | null;
            /** @example 2:3 */
            aspectRatio: string | null;
            /** @example 1K */
            imageSize: string | null;
            promptId: string | null;
            prompt: components["schemas"]["PromptDto"] | null;
            /** @example user-123 */
            userId: string;
            user: components["schemas"]["UserDto"] | null;
            files: components["schemas"]["ModelJobFile"][] | null;
            outputText: string | null;
            tariffCode: components["schemas"]["ModelJobTariffCode"];
            /** @example 8 */
            tokensCharged: number;
            usedTokens: Record<string, never> | null;
            error: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            resultsExpireAt: string | null;
            /** Format: date-time */
            resultsDeletedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            outputPreviewFiles: components["schemas"]["FileDto"][] | null;
            outputPreviewFileUrls: string[] | null;
        };
        ModelJobFullDto: {
            model: components["schemas"]["ModelType"];
            type: components["schemas"]["ModelJobType"];
            status: components["schemas"]["ModelJobStatusType"];
            text: string | null;
            /** @example 2:3 */
            aspectRatio: string | null;
            /** @example 1K */
            imageSize: string | null;
            promptId: string | null;
            prompt: components["schemas"]["PromptDto"] | null;
            /** @example user-123 */
            userId: string;
            user: components["schemas"]["UserDto"] | null;
            files: components["schemas"]["ModelJobFile"][] | null;
            outputText: string | null;
            tariffCode: components["schemas"]["ModelJobTariffCode"];
            /** @example 8 */
            tokensCharged: number;
            usedTokens: Record<string, never> | null;
            error: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            resultsExpireAt: string | null;
            /** Format: date-time */
            resultsDeletedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            inputFiles: components["schemas"]["FileDto"][] | null;
            inputFileUrls: string[] | null;
            outputFiles: components["schemas"]["FileDto"][] | null;
            outputFileUrls: string[] | null;
            outputPreviewFiles: components["schemas"]["FileDto"][] | null;
            outputPreviewFileUrls: string[] | null;
        };
        StartImageEditByPromptIdDto: {
            promptId: string;
            /**
             * @description Не более 300 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            inputFileIds: string[];
        };
        /** @enum {string} */
        ErrorCode: "TOKENS_NOT_ENOUGH" | "PAYMENT_FAILED" | "PAYMENT_PROVIDER_ERROR" | "MODEJ_JOB_TYPE_NOT_FOUND" | "MODEL_JOB_NOT_FOUND" | "MODEL_UNAVAILABLE" | "JOB_STALLED" | "PROCESSING_TIMEOUT" | "MODERATION_BLOCKED" | "INVALID_CREDENTIALS" | "UNAUTHORIZED" | "EMAIL_NOT_CONFIRMED" | "ACCOUNT_IS_BLOCKED" | "FORBIDDEN" | "EMAIL_ALREADY_EXISTS" | "PHONE_ALREADY_EXISTS" | "VALIDATION_FAILED" | "INTERNAL_SERVER_ERROR";
        ErrorInfoDto: {
            code: components["schemas"]["ErrorCode"];
            /**
             * @description Может быть undefined для бизнес-ошибок, фронт сам локализует по code
             * @example Internal server error
             */
            message?: string;
            /** @description Доп. детали, например { required: 10 } */
            details?: Record<string, never>;
        };
        ErrorResponseDto: {
            /** @example false */
            success: boolean;
            /** @example 400 */
            statusCode: number;
            error: components["schemas"]["ErrorInfoDto"];
            /** @example /api/model-job/start-image-edit-by-prompt-id */
            path: string;
            /** @example 2025-11-12T22:31:59.153Z */
            timestamp: string;
        };
        StartImageEditByPromptTextDto: {
            /**
             * @description Не более 700 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            inputFileIds: string[];
            /**
             * @description Формат
             * @example 2:3
             */
            aspectRatio: string;
            /**
             * @description Разрешение
             * @example 2K
             */
            imageSize: string;
        };
        StartImageGenerateByStyleReferenceDto: {
            inputFileIds: string[];
            /**
             * @description Формат
             * @example 2:3
             */
            aspectRatio: string;
            /**
             * @description Разрешение
             * @example 2K
             */
            imageSize: string;
        };
        StartImageGenerateByPromptTextDto: {
            /**
             * @description Не более 700 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            /**
             * @description Формат
             * @example 2:3
             */
            aspectRatio: string;
        };
        StartAdminGenerateDto: {
            /**
             * @description Не более 700 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            /**
             * @description Формат
             * @example 2:3
             */
            aspectRatio: string;
            /**
             * @description Разрешение
             * @example 2K
             */
            imageSize: string;
            inputFileIds: string[];
            model: components["schemas"]["ModelType"];
            type: components["schemas"]["ModelJobType"];
        };
        /**
         * @description Причина изменения токенов
         * @enum {string}
         */
        TokenTransactionReason: "JOB_CHARGE" | "JOB_REFUND" | "MANUAL_ADD" | "MANUAL_SUBTRACT" | "PAYMENT_PURCHASE" | "PAYMENT_REFUND" | "PROMO";
        UserTokenTransactionDto: {
            /**
             * Format: uuid
             * @description ID пользователя
             */
            userId: string;
            /** @description Пользователь (если подгружен) */
            user: components["schemas"]["UserDto"] | null;
            /**
             * @description Изменение баланса: +100 начисление, -20 списание
             * @example 50
             */
            delta: number;
            reason: components["schemas"]["TokenTransactionReason"];
            /**
             * Format: uuid
             * @description ID задачи модели, если транзакция связана с выполнением задания
             */
            modelJobId?: string | null;
            /** @description Доп. данные — тариф, промокод, пакет токенов и т.п. */
            meta?: Record<string, never> | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Уникальный идентификатор пакета
         * @enum {string}
         */
        TokensPackId: "ONCE" | "STARTER" | "BASIC" | "PRO";
        TokenPackDto: {
            /** @example STARTER */
            id: components["schemas"]["TokensPackId"];
            /**
             * @description Название пакета, отображаемое пользователю
             * @example 5 генераций
             */
            name: string;
            /**
             * @description Количество токенов в пакете
             * @example 25
             */
            tokens: number;
            /**
             * @description Ориентировочное количество генераций, которое покрывает пакет
             * @example 5
             */
            generations: number;
            /**
             * @description Скидка в процентах относительно базовой цены
             * @example 10
             */
            discountPercent: number;
            /**
             * @description Стоимость в рублях
             * @example 35
             */
            priceRub: number;
            /**
             * @description Пометить пакет как рекомендованный / выделенный
             * @example true
             */
            highlight?: boolean;
        };
        CreateCategoryDto: {
            /** @example Мультипликация */
            name: string;
            description?: string;
        };
        UpdateCategoryDto: {
            /** @example Мультипликация */
            name?: string;
            description?: string;
        };
        CreateTokensPaymentDto: {
            /**
             * @description ID пакета токенов, выбранный пользователем
             * @example pro
             */
            packId: string;
            /**
             * @description Путь на фронте, куда вернуть пользователя после оплаты. Если не указан — используем /payment/return.
             * @example /pricing
             */
            returnPath?: string;
        };
        /**
         * @description Текущий статус платежа
         * @enum {string}
         */
        PaymentStatus: "PENDING" | "WAITING_FOR_CAPTURE" | "SUCCEEDED" | "CANCELED" | "REFUNDED" | "ERROR";
        PaymentShortDto: {
            /**
             * @description ID платежа в системе Gennio
             * @example c6a6a9ff-5d9c-4a0f-9c35-6f6d1d9f7a23
             */
            id: string;
            /** @example PENDING */
            status: components["schemas"]["PaymentStatus"];
            /**
             * @description URL для перехода в YooKassa
             * @example https://yookassa.ru/checkout/...
             */
            confirmationUrl: string | null;
        };
        PaymentFullDto: {
            /**
             * Format: uuid
             * @description ID пользователя, который оплатил (или null)
             */
            userId: string | null;
            /**
             * @description Сумма платежа (numeric хранится как строка)
             * @example 199.00
             */
            amount: string;
            /**
             * @description Валюта платежа
             * @example RUB
             */
            currency: string;
            /**
             * @description Платёжный провайдер
             * @example yookassa
             */
            provider: string;
            /**
             * @description ID платежа в YooKassa
             * @example 2fbb9a6b-000f-5000-8000-1e4b4c4d01e2
             */
            providerPaymentId: string | null;
            status: components["schemas"]["PaymentStatus"];
            /**
             * @description Ссылка на страницу оплаты в YooKassa
             * @example https://yookassa.ru/checkout/...
             */
            confirmationUrl: string | null;
            /**
             * @description Описание платежа
             * @example Пакет 20 генераций
             */
            description: string | null;
            /** @description Сырой объект платежа от YooKassa */
            providerPayload: Record<string, never> | null;
            /** @description Наши внутренние данные (пакет токенов и др.) */
            meta: Record<string, never> | null;
            /** @description Сколько токенов было начислено за этот платеж */
            tokensPurchased: number | null;
            /** @description Сколько токенов уже было отозвано рефандами */
            tokensRefunded: number | null;
            /**
             * Format: date-time
             * @description Когда платеж был захвачен (capture)
             */
            capturedAt: string | null;
            /** Format: date-time */
            canceledAt: string | null;
            /** Format: date-time */
            refundedAt: string | null;
            /**
             * @description Сумма возврата
             * @example 199.00
             */
            refundedAmount: string | null;
            /**
             * @description Код ошибки от YooKassa
             * @example canceled_by_user
             */
            errorCode: string | null;
            /**
             * @description Текст ошибки
             * @example Отменено пользователем
             */
            errorMessage: string | null;
            /**
             * Format: date-time
             * @description Когда бизнес-логика была успешно выполнена
             */
            processedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["UserDto"];
        };
        PaymentDto: {
            /**
             * Format: uuid
             * @description ID пользователя, который оплатил (или null)
             */
            userId: string | null;
            /**
             * @description Сумма платежа (numeric хранится как строка)
             * @example 199.00
             */
            amount: string;
            /**
             * @description Валюта платежа
             * @example RUB
             */
            currency: string;
            /**
             * @description Платёжный провайдер
             * @example yookassa
             */
            provider: string;
            /**
             * @description ID платежа в YooKassa
             * @example 2fbb9a6b-000f-5000-8000-1e4b4c4d01e2
             */
            providerPaymentId: string | null;
            status: components["schemas"]["PaymentStatus"];
            /**
             * @description Ссылка на страницу оплаты в YooKassa
             * @example https://yookassa.ru/checkout/...
             */
            confirmationUrl: string | null;
            /**
             * @description Описание платежа
             * @example Пакет 20 генераций
             */
            description: string | null;
            /** @description Сырой объект платежа от YooKassa */
            providerPayload: Record<string, never> | null;
            /** @description Наши внутренние данные (пакет токенов и др.) */
            meta: Record<string, never> | null;
            /** @description Сколько токенов было начислено за этот платеж */
            tokensPurchased: number | null;
            /** @description Сколько токенов уже было отозвано рефандами */
            tokensRefunded: number | null;
            /**
             * Format: date-time
             * @description Когда платеж был захвачен (capture)
             */
            capturedAt: string | null;
            /** Format: date-time */
            canceledAt: string | null;
            /** Format: date-time */
            refundedAt: string | null;
            /**
             * @description Сумма возврата
             * @example 199.00
             */
            refundedAmount: string | null;
            /**
             * @description Код ошибки от YooKassa
             * @example canceled_by_user
             */
            errorCode: string | null;
            /**
             * @description Текст ошибки
             * @example Отменено пользователем
             */
            errorMessage: string | null;
            /**
             * Format: date-time
             * @description Когда бизнес-логика была успешно выполнена
             */
            processedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        YookassaWebhookResponseDto: {
            /**
             * @description Webhook успешно принят
             * @example true
             */
            accepted: boolean;
        };
        RefundTokensPreviewDto: {
            paymentId: string;
            userId: string;
            /** @description Всего токенов куплено этим платежом */
            tokensPurchased: number;
            /** @description Уже возвращено токенов по этому платежу */
            tokensRefunded: number;
            /** @description Осталось токенов, подвязанных к этому платежу */
            remainingByPayment: number;
            /** @description Текущий баланс токенов пользователя */
            userBalance: number;
            /** @description Максимум токенов, который можно вернуть сейчас */
            maxTokensToRefund: number;
            /** @description Цена одного токена по этому платежу (RUB) */
            pricePerToken: number;
            /** @description Максимальная сумма к возврату (RUB) */
            maxAmountRub: number;
            currency: string;
        };
        RefundTokensDto: {
            /**
             * @description Сколько токенов вернуть пользователю
             * @example 100
             */
            tokens: number;
            /**
             * @description Комментарий к рефанду (уходит в YooKassa)
             * @example Частичный возврат по просьбе пользователя
             */
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findMany: {
        parameters: {
            query?: {
                search?: string;
                /** @description Фильтр по роли пользователя */
                role?: components["schemas"]["UserRole"];
                /** @description Минимальное количество токенов */
                tokensMin?: number;
                /** @description Максимальное количество токенов */
                tokensMax?: number;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденный пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUserDto"];
            };
        };
        responses: {
            /** @description Пользователь заблокирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь разблокирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Пользователь не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterByEmailDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerByPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterByPhoneDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                userId: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendConfirmLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_loginByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginByEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_loginByPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginByPhoneDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_requestPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPhoneOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_verifyPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPhoneOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_redirectToYandex: {
        parameters: {
            query: {
                returnUrl: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_yandexCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    PromptsController_findMany: {
        parameters: {
            query?: {
                categoryId?: string;
                search?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PromptResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PromptsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromptDto"];
            };
        };
        responses: {
            /** @description Промпт создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
        };
    };
    PromptsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденный промпт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PromptsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Промпт удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PromptsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromptDto"];
            };
        };
        responses: {
            /** @description Обновлённый промпт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_aiUpload: {
        parameters: {
            query: {
                folder: string;
                public: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadDto"];
            };
        };
        responses: {
            /** @description Файл успешно загружен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDto"];
                };
            };
        };
    };
    FilesController_upload: {
        parameters: {
            query: {
                folder: string;
                public: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadDto"];
            };
        };
        responses: {
            /** @description Файл успешно загружен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDto"];
                };
            };
        };
    };
    FilesController_getOne: {
        parameters: {
            query: {
                signed: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDto"];
                };
            };
            /** @description Файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFileResponseDto"];
                };
            };
            /** @description Файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthcheck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModelJobController_findMany: {
        parameters: {
            query?: {
                /** @description Общий поиск */
                search?: string;
                /** @description Фильтр по типу генерации */
                type?: "image-edit-by-prompt-id" | "image-edit-by-prompt-text" | "image-edit-by-style-reference" | "image-generate-by-prompt-text";
                /** @description Фильтр по статусу генерации */
                status?: "queued" | "processing" | "succeeded" | "failed";
                /** @description Дата создания — от */
                createdFrom?: string;
                /** @description Дата создания — до */
                createdTo?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ModelJobDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    ModelJobController_lastGenerations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobWithPreviewFileDto"][];
                };
            };
        };
    };
    ModelJobController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденный процесс */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobFullDto"];
                };
            };
            /** @description Процесс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModelJobController_startImageEditByPromptId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageEditByPromptIdDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Бизнес-ошибка (например, не хватает токенов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ModelJobController_startImageEditByPromptText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageEditByPromptTextDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Бизнес-ошибка (например, не хватает токенов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ModelJobController_startImageEditByStyleReference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageGenerateByStyleReferenceDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Бизнес-ошибка (например, не хватает токенов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ModelJobController_startImageGenerateByPromptText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageGenerateByPromptTextDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Бизнес-ошибка (например, не хватает токенов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ModelJobController_startAdminGenerate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAdminGenerateDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Бизнес-ошибка (например, не хватает токенов) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UserTokenTransactionsController_findMany: {
        parameters: {
            query?: {
                /** @description Поиск по userId, email, providerPaymentId, description */
                search?: string;
                /** @description Фильтр по направлению платежа */
                delta?: number;
                /** @description Фильтр по причине платежа */
                reason?: "JOB_CHARGE" | "JOB_REFUND" | "MANUAL_ADD" | "MANUAL_SUBTRACT" | "PAYMENT_PURCHASE" | "PAYMENT_REFUND" | "PROMO";
                /** @description Дата создания — от */
                createdFrom?: string;
                /** @description Дата создания — до */
                createdTo?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserTokenTransactionDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PricingController_getTokenPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив доступных пакетов токенов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPackDto"][];
                };
            };
        };
    };
    CategoriesController_findMany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Категория создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденная категория */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категория удалёна */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Обновлённая категория */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_createTokensPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokensPaymentDto"];
            };
        };
        responses: {
            /** @description Краткая информация о платеже, включая ссылку на оплату в YooKassa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentShortDto"];
                };
            };
            /** @description Ошибка валидации или бизнес-ошибка */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PaymentsController_findMany: {
        parameters: {
            query?: {
                /** @description Поиск по userId, email, providerPaymentId, description */
                search?: string;
                /** @description Фильтр по статусу платежа */
                status?: "PENDING" | "WAITING_FOR_CAPTURE" | "SUCCEEDED" | "CANCELED" | "REFUNDED" | "ERROR";
                /** @description Дата создания — от */
                createdFrom?: string;
                /** @description Дата создания — до */
                createdTo?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PaymentFullDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PaymentsController_getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID платежа в системе Gennio */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    PaymentsController_getFullPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID платежа в системе Gennio */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentFullDto"];
                };
            };
        };
    };
    PaymentsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID платежа в системе Gennio */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    PaymentsController_yookassaWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YookassaWebhookResponseDto"];
                };
            };
        };
    };
    PaymentsController_getRefundTokensPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundTokensPreviewDto"];
                };
            };
        };
    };
    PaymentsController_refundTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundTokensDto"];
            };
        };
        responses: {
            /** @description Обновлённый платёж после запроса частичного рефанда */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentFullDto"];
                };
            };
        };
    };
    PaymentsController_refundPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Сумма возврата в рублях. Если не передана — вернуть максимально возможную сумму.
                     * @example 1000
                     */
                    amount?: number | null;
                };
            };
        };
        responses: {
            /** @description Обновлённый платёж после запроса рефанда */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentFullDto"];
                };
            };
        };
    };
    InternalYookassaController_handleInternalWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
