/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя по id */
        get: operations["UsersController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerByPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/confirm/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendConfirmLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин по email + пароль */
        post: operations["AuthController_loginByEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин по телефону + пароль */
        post: operations["AuthController_loginByPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить OTP-код для телефона */
        post: operations["AuthController_requestPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/phone/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access-токен по refresh (cookie) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти и отозвать сессию */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_redirectToYandex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/yandex/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_yandexCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список промптов с фильтрами и пагинацией */
        get: operations["PromptsController_findMany"];
        put?: never;
        /** Создать новый промпт (только админ) */
        post: operations["PromptsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один промпт по id */
        get: operations["PromptsController_findOne"];
        put?: never;
        post?: never;
        /** Удалить промпт (только админ) */
        delete: operations["PromptsController_remove"];
        options?: never;
        head?: never;
        /** Обновить промпт (только админ) */
        patch: operations["PromptsController_update"];
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FilesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить метаданные файла */
        get: operations["FilesController_getOne"];
        put?: never;
        post?: never;
        /** Удалить файл по ID */
        delete: operations["FilesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один процесс по id */
        get: operations["ModelJobController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-edit-by-prompt-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageEditByPromptId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-edit-by-prompt-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageEditByPromptText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-image-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startImageGenerateByPromptText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-job/start-text-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModelJobController_startTextGenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список категорий */
        get: operations["CategoriesController_findMany"];
        put?: never;
        /** Создать новую категорию (только админ) */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить один промпт по id */
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        /** Удалить категорию (только админ) */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /** Обновить категорию (только админ) */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "user" | "admin";
        UserDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example user@example.com */
            email?: string | null;
            yandexId?: string | null;
            /** @example +79998887766 */
            phone?: string | null;
            /** @example user */
            role: components["schemas"]["UserRole"];
            /**
             * @description Баланс кредитов
             * @example 100
             */
            credits: number;
            /**
             * @description Активен ли пользователь
             * @example true
             */
            isActive: boolean;
            /** @example false */
            isEmailVerified: boolean;
            /** @example true */
            isPhoneVerified: boolean;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        RegisterByEmailDto: {
            /** @example user@example.com */
            email: string;
            /** @example StrongPass123! */
            password: string;
        };
        RegisterByPhoneDto: {
            /** @example +79998887766 */
            phone: string;
            /**
             * @description Пароль (необязателен, если используется вход по OTP)
             * @example secretPassword123
             */
            password?: string;
        };
        LoginByEmailDto: {
            /** @example user@example.com */
            email: string;
            /** @example StrongPass123! */
            password: string;
        };
        AuthResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            user: components["schemas"]["UserDto"];
        };
        LoginByPhoneDto: {
            /** @example +79998887766 */
            phone: string;
            /** @example Secret123 */
            password: string;
        };
        RequestPhoneOtpDto: {
            /** @example +79998887766 */
            phone: string;
        };
        VerifyPhoneOtpDto: {
            /** @example +79998887766 */
            phone: string;
            /** @example 123456 */
            code: string;
        };
        PaginationMetaDto: {
            totalItems: number;
            itemCount: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
        FileDto: {
            /** @example uploads/2025/09/04/photo.png */
            key: string;
            /**
             * Format: uri
             * @example https://cdn.example.com/uploads/2025/09/04/photo.png
             */
            url?: Record<string, never> | null;
            /** @example image/png */
            contentType?: Record<string, never> | null;
            /**
             * @description Размер файла в байтах
             * @example 204800
             */
            size?: Record<string, never>;
            /** @example my-bucket */
            bucket: string;
            /** @example user-123 */
            ownerId?: Record<string, never> | null;
            /** @example {
             *       "width": 400,
             *       "height": 300
             *     } */
            meta?: Record<string, never> | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PromptType: "image-to-image" | "text-to-image" | "text-to-text";
        CategoryDto: {
            /** @example Мультипликация */
            name: string;
            /** @example Обработка изображения в рисовке мультфильмов */
            description: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PromptResponseDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            beforeImageId: string;
            beforeImage: components["schemas"]["FileDto"];
            afterImageId: string;
            afterImage: components["schemas"]["FileDto"];
            type: components["schemas"]["PromptType"];
            /** @description Текст промпта */
            text: string;
            categoryId: string;
            category: components["schemas"]["CategoryDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uri */
            beforeImageUrl: string | null;
            /** Format: uri */
            afterImageUrl: string | null;
        };
        PromptDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            beforeImageId: string;
            beforeImage: components["schemas"]["FileDto"];
            afterImageId: string;
            afterImage: components["schemas"]["FileDto"];
            type: components["schemas"]["PromptType"];
            /** @description Текст промпта */
            text: string;
            categoryId: string;
            category: components["schemas"]["CategoryDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePromptDto: {
            /** @example Аниме-портрет */
            title: string;
            /** @example Мягкое освещение, крупный план */
            description: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            afterImageId: string;
            /** @description Промпт шаблона */
            text: string;
            /** @description Категория */
            categoryId: string;
        };
        UpdatePromptDto: {
            /** @example Аниме-портрет */
            title?: string;
            /** @example Мягкое освещение, крупный план */
            description?: string;
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            afterImageId?: string;
            /** @description Промпт шаблона */
            text?: string;
            /** @description Категория */
            categoryId?: string;
        };
        UploadDto: {
            /** Format: binary */
            file: string;
        };
        UploadFileResponseDto: {
            /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
            id: string;
            /** @example uploads/2025/09/04/file.png */
            key: string;
            /** @example https://cdn.example.com/uploads/2025/09/04/file.png */
            url: Record<string, never> | null;
            /** @example image/png */
            contentType: Record<string, never> | null;
            /**
             * @description Размер файла в байтах
             * @example 204800
             */
            size: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        DeleteFileResponseDto: {
            /** @example true */
            ok: boolean;
            /**
             * @description UUID удалённого файла
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            id: string;
        };
        /** @enum {string} */
        ModelType: "OPENAI";
        /** @enum {string} */
        ModelJobType: "image-edit-by-prompt-id" | "image-edit-by-prompt-text" | "image-generate-by-prompt-text" | "text-generate";
        /** @enum {string} */
        ModelJobStatusType: "queued" | "processing" | "succeeded" | "failed";
        /**
         * @description Тариф, по которому считали стоимость задачи
         * @enum {string}
         */
        ModelTariffCode: "TEXT_BASIC" | "TEXT_PRO" | "IMAGE_BASIC_GENERATE" | "IMAGE_BASIC_EDIT" | "IMAGE_PRO_GENERATE" | "IMAGE_PRO_EDIT";
        ModelJobDto: {
            model: components["schemas"]["ModelType"];
            type: components["schemas"]["ModelJobType"];
            status: components["schemas"]["ModelJobStatusType"];
            /** @example Мягкое освещение, крупный план */
            text: string | null;
            /** @example Мягкое освещение, крупный план */
            promptId: string | null;
            /** @example user-123 */
            userId: string;
            /**
             * Format: uuid
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            inputFileId: string | null;
            /**
             * Format: uuid
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            outputFileId: string | null;
            /**
             * Format: uuid
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            outputPreviewFileId: string | null;
            /** @example https://cdn.example.com/jobs/2025/09/19/5139b0d6-f38d-4af1.jpeg */
            inputFileUrl: string | null;
            /** @example https://cdn.example.com/jobs/2025/09/19/5139b0d6-f38d-4af1.jpeg */
            outputFileUrl: string | null;
            /** @example https://cdn.example.com/jobs/2025/09/19/5139b0d6-f38d-4af1.jpeg */
            outputPreviewFileUrl: string | null;
            outputText: string | null;
            tariffCode: components["schemas"]["ModelTariffCode"];
            /**
             * @description Сколько кредитов списано за эту задачу
             * @example 8
             */
            creditsCharged: number;
            /** @example OpenAI timeout error */
            error: Record<string, never> | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StartImageEditByPromptIdDto: {
            model: components["schemas"]["ModelType"];
            promptId: string;
            /**
             * @description Не более 500 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            inputFileId: string;
        };
        StartImageEditByPromptTextDto: {
            model: components["schemas"]["ModelType"];
            /**
             * @description Не более 500 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
            inputFileId: string;
        };
        StartImageGenerateByPromptTextDto: {
            model: components["schemas"]["ModelType"];
            /**
             * @description Не более 500 символов
             * @example Мягкое освещение, крупный план
             */
            text: string;
        };
        StartTextGenerateDto: {
            model: components["schemas"]["ModelType"];
            /**
             * @description Не более 500 символов
             * @example Сгенерируй текст новогоднего поздравления
             */
            text: string;
        };
        CreateCategoryDto: {
            /** @example Мультипликация */
            name: string;
            description?: string;
        };
        UpdateCategoryDto: {
            /** @example Мультипликация */
            name?: string;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_registerByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterByEmailDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerByPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterByPhoneDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                userId: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendConfirmLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_loginByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginByEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_loginByPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginByPhoneDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_requestPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPhoneOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_verifyPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPhoneOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_redirectToYandex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_yandexCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PromptsController_findMany: {
        parameters: {
            query?: {
                categoryId?: string;
                search?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PromptResponseDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PromptsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromptDto"];
            };
        };
        responses: {
            /** @description Промпт создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
        };
    };
    PromptsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденный промпт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PromptsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Промпт удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PromptsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromptDto"];
            };
        };
        responses: {
            /** @description Обновлённый промпт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDto"];
                };
            };
            /** @description Промпт не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_upload: {
        parameters: {
            query: {
                folder: string;
                public: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadDto"];
            };
        };
        responses: {
            /** @description Файл успешно загружен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadFileResponseDto"];
                };
            };
        };
    };
    FilesController_getOne: {
        parameters: {
            query: {
                signed: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDto"];
                };
            };
            /** @description Файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл удалён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFileResponseDto"];
                };
            };
            /** @description Файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthcheck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModelJobController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденный процесс */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
            /** @description Процесс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModelJobController_startImageEditByPromptId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageEditByPromptIdDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
        };
    };
    ModelJobController_startImageEditByPromptText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageEditByPromptTextDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
        };
    };
    ModelJobController_startImageGenerateByPromptText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImageGenerateByPromptTextDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
        };
    };
    ModelJobController_startTextGenerate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTextGenerateDto"];
            };
        };
        responses: {
            /** @description Генерация запущена */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelJobDto"];
                };
            };
        };
    };
    CategoriesController_findMany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Категория создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденная категория */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Категория удалёна */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Обновлённая категория */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Категория не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
